default_config:
http:
  server_port:                   8123

logger:
  default:                         debug
  logs:
    # log level for HA core
    homeassistant.core:            debug

    # log level for this custom component
    custom_components.hdmimatrix:  debug

    # log level for the `aiohttp` Python package
    aiohttp:                       debug

hdmimatrix:                      !include hdmimatrix.yaml
